# Generated by Django 4.2.21 on 2025-05-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='apply_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
