# Generated by Django 4.2.21 on 2025-05-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_jobposting_apply_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
