# Generated by Django 4.2.21 on 2025-05-17 07:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_jobposting_apply_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-posting_date'], 'verbose_name': 'job posting', 'verbose_name_plural': 'job postings'},
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='job_posting_search__8d84a0_gin'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company'], name='job_posting_company_d7d101_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_active'], name='job_posting_is_acti_452b29_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['expiration_date'], name='job_posting_expirat_01f51e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['posting_date'], name='job_posting_posting_89758a_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'title'), name='unique_active_job_title_per_company'),
        ),
    ]
