# Generated by Django 4.2.21 on 2025-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_jobposting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_name_cached',
            field=models.CharField(default='公司1', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
