# Generated by Django 4.2.21 on 2025-05-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_logo_url_alter_company_website'),
        ('api', '0004_jobposting_company_name_cached'),
    ]

    operations = [
    ]
